version: '3.8'

services:
  db:
    build: .
    restart: on-failure
    ports:
      - 5000:8000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db/postgres"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data:cached

